"""MetaTrader 5 connector package."""

from src.trading.connectors.mt5.sdk import (
    MT5Config,
    MT5ConnectionError,
    MT5DependencyError,
    MT5ProfileMismatchError,
    build_config,
    cancel_order,
    check_status,
    close_position,
    contract_size,
    get_account_snapshot,
    get_historical_bars,
    get_historical_bars_range,
    get_open_orders,
    get_positions,
    get_quote,
    load_config,
    modify_position,
    mt5_available,
    place_order,
    save_config,
)

__all__ = [
    "MT5Config",
    "MT5ConnectionError",
    "MT5DependencyError",
    "MT5ProfileMismatchError",
    "build_config",
    "cancel_order",
    "check_status",
    "close_position",
    "contract_size",
    "get_account_snapshot",
    "get_historical_bars",
    "get_historical_bars_range",
    "get_open_orders",
    "get_positions",
    "get_quote",
    "load_config",
    "modify_position",
    "mt5_available",
    "place_order",
    "save_config",
]
